.pragma library

var COUNTER_NOT_FOUND = 108;
var ENDPOINT_NOT_FOUND = 104;
var NOT_AUTHENTICATED_REQUEST = 105;
var NOT_VALID_REQUEST = 100;
var OTP = 3;
var REGISTRATION_NOT_FOUND = 101;
var REQUEST_FAILED = 106;
var REQUEST_PARAMS_NOT_VALID = 103;
var SERVER_ERROR = 300;
var SERVICE_TEMPORARILY_UNAVAILABLE = 200;
var SESSION_NOT_FOUND = 102;
